ADJECTIVES = [
    # Original bass-themed adjectives
    "Chunky", "Crusty", "Beefy", "Thicc", "Filthy", "Rancid", "Greasy",
    "Soggy", "Moldy", "Sloppy", "Grungy", "Musty", "Swampy", "Muddy",
    "Stanky", "Grimy", "Rusty", "Crushed", "Mangled", "Destroyed",
    "Obliterated", "Massacred", "Annihilated", "Pulverized", "Shredded",
    "Warped", "Twisted", "Bent", "Broken", "Cursed", "Haunted", "Possessed",
    "Angry", "Violent", "Aggressive", "Feral", "Savage", "Brutal", "Nasty",
    "Abnormal", "Abrasive", "Abrupt", "Absurd", "Abundant", "Abusive",
    "Addicted", "Adorable", "Adventurous", "Afraid", "Agonizing", "Alcoholic",
    "Annoying", "Anxious", "Arrogant", "Ashamed", "Astonishing",
    "Auspicious", "Automatic", "Awesome", "Awful", "Axiomatic", "Barbarous",
    "Beautiful", "Belligerent", "Bitter", "Bizarre", "Bloody",
    "Blushing", "Boiling", "Boorish", "Bored", "Boring", "Bouncy",
    "Capricious", "Careful", "Careless", "Caring", "Cautious", "Ceaseless",
    "Cheap", "Busty", "Chivalrous", "Chubby", "Clammy", "Classy", "Clean",
    "Clever", "Clumsy", "Colossal", "Confused", "Cool", "Cowardly", "Crabby",
    "Crazy", "Creepy", "Crooked", "Crowded", "Cruel", "Cuddly", "Cultured", "Cumbersome",
    "Curious", "Curly", "Curved", "Curvy", "Cute", "Cynical", "Damaged", "Damaging", "Damp",
    "Dangerous", "Dapper", "Dark", "Dashing", "Dazzling", "Dead", "Deadpan",
    "Deafening", "Debonair", "Decisive", "Decorous", "Deep", "Defeated",
    "Defective", "Defiant", "Delicate", "Delicious", "Delightful", "Demonic",
    "Deranged", "Descriptive", "Deserted", "Detailed", "Determined", "Devilish",
    "Difficult", "Diligent", "Dirty", "Discreet", "Disgusting", "Disillusioned",
    "Distinct", "Disturbed", "Drunk", "Dry", "Dull", "Dusty", "Dysfunctional",
    "Eager", "Earthy", "Easy", "Efficient", "Elderly", "Embarrassed", "Elitest",
    "Eminent", "Empty", "Enchanted", "Enchanting", "Encouraging", "Endurable",
    "Enormous", "Erotic", "Fabulous", "Faded", "Phallic", "Fancy", "Fantastic",
    "Fascinated", "Fast", "Fat", "Faulty", "Fearful", "Fearless", "Fertile", "Festive",
    "Fierce", "Flaky", "Flashy", "Flat-Chested", "flatulent", "Foamy", "Foolish",
    "Fragile", "Frantic", "Free", "Freezing", "Frequent", "Fresh",
    "Fuzzy", "Gaping", "Gaudy", "Pregnant", "Racist", "Lesbian",
    "Giant", "Giddy", "Gifted", "Gigantic", "Glamorous", "Gleaming",
    "Glib", "Glistening", "Glorious", "Glossy", "Godly", "Good",
    "Goofy", "Gorgeous", "Graceful", "Grandiose", "Grateful",
    "Gray", "Great", "Greedy", "Green", "Grey", "Grieving", "Groovy", "Grotesque",
    "Grouchy", "Grubby", "Gruesome", "Grumpy", "Breast-Feeding", "Gay",
    "Guarded", "Guiltless", "Gullible", "Gusty", "Guttural", "Habitual",
    "Happy", "Hard", "Harsh", "Hateful", "Hairless", "Homeless", "Ugly",
    "Honorable", "Horrible", "Hospitable", "Hot", "Huge", "Hungry", "Hurried",
    "Husky", "Hangry", "Icky", "Idiotic", "Ignorant", "Ill", "Illegal", "Imaginary", "Immense",
    "Imminent", "Impartial", "Imperfect", "Impolite", "Important", "Imported",
    "Incompetent", "Inconclusive", "Incredible", "incontinent", "Innocent", "Inquisitive",
    "Insidious", "Intelligent", "Interesting", "Itchy", "Jaded", "Jagged", "Jazzy", "Jealous",
    "Jittery", "Jobless", "Juicy", "Knotty", "Knowing", "Knowledgeable", "Known", "Kinky",
    "Large", "Last", "Late", "Laughable", "Lavish", "Lazy", "Lean", "Learned", "Left",
    "Legal", "Barely-Legal", "Lewd", "Light", "Likeable", "Limping", "Literate", "Little",
    "Lively", "Living", "Lonely", "Long", "Longing", "Loose",
    "Lopsided", "Loud", "Loutish", "Lovely", "Loving", "Low", "Lowly", "Lucky", "Ludicrous",
    "Lumpy", "Lush", "Luxuriant", "Macho", "Manly", "Madly", "Magical", "Magnificent",
    "Majestic", "Makeshift", "Male", "Malicious", "Mammoth", "Maniacal", "Many", "Marked", "Massive",
    "Mean", "Measly", "Meaty", "Medical", "Meek", "Mellow", "Melodic", "Messy", "Mighty", "Military",
    "Milky", "Mindless", "Miniature", "Minor", "Miscreant", "Misty", "Mixed", "Moaning", "Modern",
    "Momentous", "Motionless", "Mountainous", "Muddled", "Mundane",
    "Murky", "Mushy", "Mute", "Mysterious", "Naked", "Nappy", "Narrow", "Natural", "Naughty", "Nauseating",
    "Near", "Neat", "Nebulous", "Necessary", "Needless", "Needy",
    "Neighborly", "Nervous", "New", "Nice", "Nifty", "Nimble",
    "Nippy", "Nondescript", "Nonstop", "Nutritious", "Nutty", "Oafish", "Obedient", "Obeisant",
    "Obese", "Obnoxious", "Obscene", "Obsequious", "Observant", "Obsolete",
    "Obtainable", "Oceanic", "Odd", "Offbeat", "Old", "Omniscient",
    "Onerous", "Open", "Opposite", "Optimal", "Orange", "Ordinary",
    "Organic", "Ossified", "Outgoing", "Outrageous", "Outstanding", "Oval",
    "Overconfident", "Overjoyed", "Overrated", "Overt", "Overwrought", "Painful",
    "Painstaking", "Pale", "Paltry", "Panicky", "Panoramic", "Parallel",
    "Parched", "Parsimonious", "Past", "Pastoral", "Pathetic", "Peaceful",
    "Penitent", "Perfect", "Periodic", "Permissible", "Perpetual", "Petite",
    "Phobic", "Physical", "Picayune", "Pink", "Piquant", "Placid",
    "Plain", "Plastic", "Plausible", "Pleasant", "Plucky", "Pointless",
    "Poised", "Polite", "Political", "Poor", "Possessive", "Possible",
    "Powerful", "Precious", "Premium", "Present", "Pretty", "Previous",
    "Pricey", "Prickly", "Private", "Probable", "Productive", "Profuse",
    "Protective", "Proud", "Psychedelic", "Psychotic", "Public", "Puffy",
    "Pumped", "Puny", "Purple", "Purring", "Pushy", "Puzzled",
    "Puzzling", "Quack", "Quaint", "Quarrelsome", "Questionable", "Quick",
    "Quickest", "Quiet", "Quirky", "Quixotic", "Quizzical", "Rabid",
    "Racial", "Ragged", "Rainy", "Rambunctious", "Rampant", "Rapid",
    "Rare", "Raspy", "Ratty", "Ready", "Real", "Rebel",
    "Receptive", "Recondite", "Red", "Redundant", "Reflective", "Regular",
    "Relieved", "Remarkable", "Reminiscent", "Repulsive", "Resolute", "Resonant",
    "Responsible", "Rhetorical", "Rich", "Right", "Righteous", "Rightful",
    "Rigid", "Ripe", "Ritzy", "Roasted", "Robust", "Romantic",
    "Roomy", "Rotten", "Rough", "Round", "Royal", "Ruddy",
    "Rude", "Rural", "Rustic", "Ruthless", "Sable", "Sad",
    "Safe", "Salty", "Same", "Sassy", "Satisfying", "Savory",
    "Scandalous", "Scarce", "Scared", "Scary", "Scattered", "Scientific",
    "Scintillating", "Scrawny", "Screeching", "Secret", "Secretive", "Sedate",
    "Seemly", "Selective", "Selfish", "Separate", "Serious", "Shaggy",
    "Shaky", "Shallow", "Sharp", "Shiny", "Shivering", "Shocking",
    "Short", "Shrill", "Shut", "Shy", "Sick", "Silent", "Soupy",
    "Silky", "Silly", "Simple", "Simplistic", "Sincere", "Skillful",
    "Skinny", "Sleepy", "Slim", "Slimy", "Slippery", "Slow", "Slutty",
    "Small", "Smart", "Smelly", "Smiling", "Smoggy", "Smooth",
    "Sneaky", "Snobbish", "Snotty", "Soft", "Solid", "Somber",
    "Sophisticated", "Sordid", "Sore", "Sour", "Sparkling", "Special",
    "Spectacular", "Spicy", "Spiffy", "Spiky", "Spiritual", "Spiteful",
    "Splendid", "Spooky", "Spotless", "Spotted", "Spotty", "Spurious",
    "Squalid", "Square", "Squealing", "Squeamish", "Staking", "Stale",
    "Standing", "Statuesque", "Steadfast", "Steady", "Steep", "Stereotyped",
    "Sticky", "Stiff", "Stimulating", "Stingy", "Stormy", "Straight",
    "Strange", "Striped", "Strong", "Stupendous", "Stupid", "Sturdy",
    "Subdued", "Subsequent", "Substantial", "Successful", "Succinct", "Sudden",
    "Sulky", "Super", "Superb", "Superficial", "Supreme", "Swanky",
    "Sweet", "Sweltering", "Swift", "Symptomatic", "Synonymous", "Taboo",
    "Tacit", "Tacky", "Talented", "Tall", "Tame", "Tan",
    "Tangible", "Tangy", "Tart", "Tasteful", "Tasteless", "Tasty",
    "Tawdry", "Tearful", "Tedious", "Teeny", "Telling", "Temporary",
    "Ten", "Tender", "Tense", "Tenuous", "Terrible", "Terrific",
    "Tested", "Testy", "Thankful", "Therapeutic", "Thick", "Thin",
    "Thinkable", "Third", "Thirsty", "Thoughtful", "Thoughtless", "Threatening",
    "Three", "Thundering", "Tidy", "Tight", "Tightfisted", "Tiny",
    "Tired", "Tiresome", "Toothsome", "Torpid", "Tough", "Towering",
    "Tranquil", "Trashy", "Tremendous", "Tricky", "Trite", "Troubled",
    "Truculent", "True", "Truthful", "Two", "Typical", "Ubiquitous",
    "Ugliest", "Ugly", "Ultra", "Unable", "Unaccountable", "Unadvised",
    "Unarmed", "Unbecoming", "Unbiased", "Uncovered", "Understood", "Undesirable",
    "Unequal", "Unequaled", "Uneven", "Unhealthy", "Uninterested", "Unique",
    "Unkempt", "Unknown", "Unnatural", "Unruly", "Unsightly", "Unsuitable",
    "Untidy", "Unused", "Unusual", "Unwieldy", "Unwritten", "Upbeat",
    "Uppity", "Upset", "Uptight", "Used", "Useful", "Useless",
    "Utopian", "Utter", "Uttermost", "Vacuous", "Vagabond", "Vague",
    "Valuable", "Various", "Vast", "Vengeful", "Venomous", "Verdant",
    "Versed", "Victorious", "Vigorous", "Violet", "Vivacious", "Voiceless",
    "Volatile", "Voracious", "Vulgar", "Wacky", "Waggish", "Waiting",
    "Wakeful", "Wandering", "Wanting", "Warlike", "Warm", "Wary",
    "Wasteful", "Watery", "Weak", "Wealthy", "Weary", "Wet",
    "Whimsical", "Whispering", "White", "Whole", "Wholesale", "Wicked",
    "Wide", "Wiggly", "Wild", "Willing", "Windy", "Wiry",
    "Wise", "Wistful", "Witty", "Woebegone", "Womanly", "Wonderful",
    "Wooden", "Woozy", "Workable", "Worried", "Worthless", "Wrathful",
    "Wretched", "Wrong", "Wry", "Yellow", "Yielding", "Young",
    "Youthful", "Yummy", "Zany", "Zealous", "Zesty", "Zippy", "Zonked"
]

# Expanded noun list
NOUNS = [
    # Original nouns
    "Chungus", "Goblin", "Troll", "Ogre", "Demon", "Beast", "Monster",
    "Creature", "Abomination", "Nightmare", "Horror", "Menace", "Fiend",
    "Lurker", "Dweller", "Thingy", "Blob", "Ooze", "Sludge", "Gunk",
    "Chaos", "Void", "Abyss", "Darkness", "Shadow", "Wraith", "Phantom",
    "Boi", "Bro", "Dude", "Guy", "Homie", "Buddy", "Pal", "Champ", "Cowboy",
    "Unit", "Specimen", "Entity", "Being", "Presence", "Force", "Energy",
    "Doggo", "Floof", "Hooman", "Yeet", "Ratchet", "Derp", "Catfish",
    "Stan", "Flex", "Smol", "Chonk", "Hippy", "Wook", "Raver",
    "Candykid", "Banger", "Skid", "Emo", "Punk", "Metalhead", "balls",
    "Baby_Batter", "Nipples", "Under_boob", "Tiddies", "Man-Child", "Dong",
    "Hot_Dog", "Rapper", "Skeet", "Discharge", "Grimmus", "Hole", "Turd", "DJ",
    "Wizard", "Chump", "Chump_Soup", "Chick", "Bimbo", "MILF", "Influencer", "E_Girl",
    "Karen", "Monkey", "Donkey", "Stoner", "Tweaker", "Stripper", "Prostitute", "Support_Group",
]

# Expanded suffix list
SUFFIXES = [
    # Original suffixes
    "ofDoom", "of_Chaos", "of_Destruction", "of_Death", "of_Despair", "Anonymous",
    "from_Hell", "fromtheVoid", "fromtheAbyss", "fromBelow", "Fucker", "League",
    "Destroyer", "Annihilator", "Obliterator", "Decimator", "Eradicator", "Collectable_Action_Figure",
    "Supreme", "Ultimate", "Mega", "Ultra", "Hyper", "Super", "Maximum", "Sex_Tape",
    "9000", "XL", "XXL", "Pro", "Plus", "Deluxe", "Premium", "Elite", "Berg",
    "the_Third", "Esquire", "Lite", "Junior", "ington", "sucker", "licker", "taster",
    "Gazer", "Groper", "Toucher", "Er", "Est", "Ie", "Collector", "Fan_Club", "Megazine"
]
